#pragma once
#define UHE_MOUSE_BUTTON_1         0
#define UHE_MOUSE_BUTTON_2         1
#define UHE_MOUSE_BUTTON_3         2
#define UHE_MOUSE_BUTTON_4         3
#define UHE_MOUSE_BUTTON_5         4
#define UHE_MOUSE_BUTTON_6         5
#define UHE_MOUSE_BUTTON_7         6
#define UHE_MOUSE_BUTTON_8         7
#define UHE_MOUSE_BUTTON_LAST      UHE_MOUSE_BUTTON_8
#define UHE_MOUSE_BUTTON_LEFT      UHE_MOUSE_BUTTON_1
#define UHE_MOUSE_BUTTON_RIGHT     UHE_MOUSE_BUTTON_2
#define UHE_MOUSE_BUTTON_MIDDLE    UHE_MOUSE_BUTTON_3